### ISSUE TITLE
prompt_frost_setup:shift:1: shift count must be <= $#

### ISSUE THREAD

**Issue by tjuberg** [TomFrost/frost-zsh-prompt#1]
Upon setting: prompt frost

The following error occurs:
prompt_frost_setup:shift:1: shift count must be <= $#

zsh 5.3.1 (x86_64-unknown-linux-gnu)
Arch Linux

**Comment by TomFrost** [comment]
Interesting! Have you tried [Pure](https://github.com/sindresorhus/pure), and do you get the same error with it? I'll do some more testing on my side!

(Also, if you don't mind my asking, how did you discover this prompt? I've barely told anyone it existed yet xD)

**Comment by tjuberg** [comment]
I'll have a closer look tomorrow.
Interestingly I cannot reproduce this on my second system which is also an Arch install, so it might be some odd fluke on my work machine.

As for this prompt, I've been following you since I originally discovered https://gist.github.com/TomFrost/9472926 some 3 years ago or so, and the repo happened to be on the top of my github feed last night :+1:

**Comment by TomFrost** [comment]
Ha, no kidding! I didn't realize my old Prezto theme had any users other than me :). I recently dropped Prezto in favor of a framework-free config powered by [Antibody](https://github.com/getantibody/antibody), so a rewrite to my theme was in order since it relied on Prezto pretty heavily.

With that said, could you share how you're installing the theme on your work machine? Is it through a framework, a plugin manager like Antibody/Antigen, or fully manually?

**Comment by tjuberg** [comment]
I've migrated more or less away from Prezto myself, although I still use some of it's modules.

I currently use [zplug](https://github.com/zplug/zplug) to install the prompt, but I suspect the issue on the work machine was caused by PEBKAC and possibly something interfering from my old configuration that I had missed. I'll check again in the morning.

**Comment by tjuberg** [comment]
Confirming that this was an error on my end and caused by a lingering prezto prompt call that I missed several times when looking.

Apologies for wasting your time.

**Comment by TomFrost** [comment]
Not a waste at all! I got to discover that someone else uses my prompt but me, and that the term PEBKAC is so pervasive it's literally used around the world :).

All the best!
